import ExcelJS from "exceljs";

import {
  excelSafeText,
  type MonthlyMetrics,
  type RegistryFilters,
  type RegistryRow,
  type RegistryTotals,
} from "./domain";

export const CONTRACT_HEADERS = [
  "Application Number", "Contract Number", "Contract Date", "Counterparty",
  "INN", "Bank Account", "Subject", "Amount", "Currency",
  "Application Status", "Contract Status", "Version", "Generated At",
  "Approved At", "Sent At", "Specialist", "Template", "Template Type",
  "Completeness %", "Conflicts", "Application ID", "Contract ID", "Version ID",
] as const;

type WorkbookInput = {
  rows: RegistryRow[];
  totals: RegistryTotals;
  metrics: MonthlyMetrics;
  filters: RegistryFilters;
  generatedBy: string;
  generatedAt?: Date;
  fingerprint: string;
};

function date(value: string | null) {
  return value ? new Date(value) : null;
}

function styleHeader(row: ExcelJS.Row) {
  row.font = { bold: true, color: { argb: "FFFFFFFF" } };
  row.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1957A6" } };
  row.alignment = { vertical: "middle", wrapText: true };
}

function sortedEntries(values: Record<string, number>) {
  return Object.entries(values).sort(([a], [b]) => a.localeCompare(b));
}

export async function buildContractReportWorkbook(input: WorkbookInput) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Tax Agency Automation";
  workbook.created = input.generatedAt ?? new Date();
  workbook.calcProperties.fullCalcOnLoad = true;

  const contracts = workbook.addWorksheet("Contracts", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  contracts.addRow(CONTRACT_HEADERS);
  styleHeader(contracts.getRow(1));
  for (const row of input.rows) {
    contracts.addRow([
      excelSafeText(row.application_number),
      excelSafeText(row.contract_number),
      date(row.contract_date),
      excelSafeText(row.counterparty_name),
      excelSafeText(row.inn),
      excelSafeText(row.bank_account),
      excelSafeText(row.contract_subject),
      row.contract_amount,
      excelSafeText(row.currency),
      excelSafeText(row.application_status),
      excelSafeText(row.contract_status),
      row.version_number,
      date(row.generated_at),
      date(row.approved_at),
      date(row.sent_at),
      excelSafeText(row.specialist_name ?? row.specialist_email),
      excelSafeText(row.template_name),
      excelSafeText(row.template_type),
      row.completeness_percentage,
      row.has_conflicts ? "Yes" : "No",
      excelSafeText(row.application_id),
      excelSafeText(row.contract_id),
      excelSafeText(row.current_version_id),
    ]);
  }
  contracts.autoFilter = { from: "A1", to: "W1" };
  contracts.columns.forEach((column, index) => {
    column.width = [20, 20, 14, 34, 16, 24, 36, 16, 11, 22, 18, 10, 20, 20, 20, 28, 28, 18, 16, 12, 38, 38, 38][index];
  });
  ["C", "M", "N", "O"].forEach((column) => {
    contracts.getColumn(column).numFmt = column === "C" ? "yyyy-mm-dd" : "yyyy-mm-dd hh:mm";
  });
  contracts.getColumn("H").numFmt = "#,##0.00";
  ["A", "B", "E", "F", "U", "V", "W"].forEach((column) => {
    contracts.getColumn(column).numFmt = "@";
  });
  contracts.eachRow((row, number) => {
    if (number > 1) row.alignment = { vertical: "top", wrapText: true };
  });

  const summary = workbook.addWorksheet("Summary", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  summary.columns = [{ width: 34 }, { width: 26 }];
  summary.addRow(["Metric", "Value"]);
  styleHeader(summary.getRow(1));
  const summaryRows: Array<[string, string | number | Date | null]> = [
    ["Period start", date(input.filters.dateFrom ?? null)],
    ["Period end", date(input.filters.dateTo ?? null)],
    ["Generated by", excelSafeText(input.generatedBy)],
    ["Generated at", input.generatedAt ?? new Date()],
    ["Data fingerprint", input.fingerprint],
    ["Applications", input.totals.applicationCount],
    ["Contracts", input.totals.contractCount],
    ["Approved contracts", input.totals.approvedContractCount],
    ["Applications without contract", input.totals.unpreparedApplicationCount],
    ["Applications with conflicts", input.totals.conflictApplicationCount],
    ["New applications", input.metrics.newApplications],
    ["Processed applications", input.metrics.processedApplications],
    ["Sent contracts", input.metrics.sentContracts],
    ["Waiting for client", input.metrics.waitingForClient],
    ["Manual review", input.metrics.manualReview],
    ["Rejected contracts", input.metrics.rejectedContracts],
    ["Clarification emails", input.metrics.clarificationEmails],
    ["Repeated clarifications", input.metrics.repeatedClarifications],
    ["Average processing hours", input.metrics.averageProcessingHours],
  ];
  for (const [currency, amount] of sortedEntries(input.metrics.amountsByCurrency)) {
    summaryRows.push([`Contract amount (${currency})`, amount]);
  }
  for (const [type, count] of sortedEntries(input.metrics.contractsByTemplateType)) {
    summaryRows.push([`Template type: ${type}`, count]);
  }
  for (const [specialist, count] of sortedEntries(input.metrics.workBySpecialist)) {
    summaryRows.push([`Specialist: ${excelSafeText(specialist)}`, count]);
  }
  summary.addRows(summaryRows);
  summary.getColumn("B").numFmt = "General";
  summary.getCell("B2").numFmt = "yyyy-mm-dd";
  summary.getCell("B3").numFmt = "yyyy-mm-dd";
  summary.getCell("B5").numFmt = "yyyy-mm-dd hh:mm";
  summary.eachRow((row, number) => {
    if (number > 1) row.alignment = { vertical: "top", wrapText: true };
  });
  return workbook;
}

export async function serializeContractReport(input: WorkbookInput) {
  const workbook = await buildContractReportWorkbook(input);
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

export async function verifyContractReport(content: Buffer) {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(content as unknown as ExcelJS.Buffer);
  const contracts = workbook.getWorksheet("Contracts");
  const summary = workbook.getWorksheet("Summary");
  if (!contracts || !summary) throw new Error("REPORT_SHEETS_MISSING");
  const headerValues = contracts.getRow(1).values;
  if (!Array.isArray(headerValues) ||
      headerValues.slice(1).join("|") !== CONTRACT_HEADERS.join("|")) {
    throw new Error("REPORT_HEADERS_INVALID");
  }
  if (contracts.rowCount > 1) {
    const first = contracts.getRow(2);
    if (first.getCell(8).value !== null && typeof first.getCell(8).value !== "number") {
      throw new Error("REPORT_AMOUNT_TYPE_INVALID");
    }
    const value = first.getCell(3).value;
    if (value !== null && !(value instanceof Date)) throw new Error("REPORT_DATE_TYPE_INVALID");
  }
  return { contractRows: Math.max(0, contracts.rowCount - 1), summaryRows: summary.rowCount - 1 };
}
